# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from scenario.FFP import modIdentify_pb2 as scenario_dot_FFP_dot_modIdentify__pb2
from scenario import scenario_pb2 as scenario_dot_scenario__pb2


class ModulationIdentifyServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartModIdentifyTask = channel.unary_unary(
                '/zb.dcts.scenario.FFP.ModulationIdentifyService/StartModIdentifyTask',
                request_serializer=scenario_dot_FFP_dot_modIdentify__pb2.ModIdentifyRequest.SerializeToString,
                response_deserializer=scenario_dot_scenario__pb2.ScenarioReply.FromString,
                )
        self.StopModIdentifyTask = channel.unary_unary(
                '/zb.dcts.scenario.FFP.ModulationIdentifyService/StopModIdentifyTask',
                request_serializer=scenario_dot_scenario__pb2.ScenarioTaskId.SerializeToString,
                response_deserializer=scenario_dot_scenario__pb2.ScenarioReply.FromString,
                )


class ModulationIdentifyServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def StartModIdentifyTask(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopModIdentifyTask(self, request, context):
        """rpc GetModIdentifyResult(ScenarioTaskId) returns (ModIdentifyResult) {}
        rpc GetModIdentifySpectrum(ScenarioTaskId) returns (stream ModIdentifyResult) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModulationIdentifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartModIdentifyTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StartModIdentifyTask,
                    request_deserializer=scenario_dot_FFP_dot_modIdentify__pb2.ModIdentifyRequest.FromString,
                    response_serializer=scenario_dot_scenario__pb2.ScenarioReply.SerializeToString,
            ),
            'StopModIdentifyTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopModIdentifyTask,
                    request_deserializer=scenario_dot_scenario__pb2.ScenarioTaskId.FromString,
                    response_serializer=scenario_dot_scenario__pb2.ScenarioReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zb.dcts.scenario.FFP.ModulationIdentifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModulationIdentifyService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def StartModIdentifyTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zb.dcts.scenario.FFP.ModulationIdentifyService/StartModIdentifyTask',
            scenario_dot_FFP_dot_modIdentify__pb2.ModIdentifyRequest.SerializeToString,
            scenario_dot_scenario__pb2.ScenarioReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopModIdentifyTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zb.dcts.scenario.FFP.ModulationIdentifyService/StopModIdentifyTask',
            scenario_dot_scenario__pb2.ScenarioTaskId.SerializeToString,
            scenario_dot_scenario__pb2.ScenarioReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
